export const REQUEST_LOGIN = 'AUTH/REQUEST_LOGIN';
export const REQUEST_REGISTER = 'AUTH/REQUEST_REGISTER';
export const REQUEST_LOGOUT = 'AUTH/REQUEST_LOGOUT';
export const REQUEST_CHECK_AUTH = 'AUTH/REQUEST_CHECK_AUTH';
export const SET_AUTH_USER = 'AUTH/SET_AUTH_USER';
export const LOGOUT_AUTH_USER = 'AUTH/LOGOUT_AUTH_USER';
export const SHOW_SESSION_LOADING = 'AUTH/SHOW_SESSION_LOADING';
export const HIDE_SESSION_LOADING = 'AUTH/HIDE_SESSION_LOADING';

export const REQUEST_CREATE_POST = 'POST/REQUEST_CREATE_POST';
export const SHOW_CREATE_POST_LOADING = 'POST/SHOW_CREATE_POST_LOADING';
export const HIDE_CREATE_POST_LOADING = 'POST/HIDE_CREATE_POST_LOADING';
export const REQUEST_GET_POST = 'POST/REQUEST_GET_POST';
export const SET_POST_PAGE = 'POST/SET_POST_PAGE';
export const REQUEST_LIKE_POST = 'POST/REQUEST_LIKE_POST';

export const REQUEST_GET_PROFILE_INFO = 'PROFILE/REQUEST_GET_PROFILE_INFO';
export const REQUEST_GET_USER_POSTS = 'PROFILE/REQUEST_GET_USER_POSTS';
export const SET_PROFILE_INFO = 'PROFILE/SET_PROFILE_INFO';
export const SET_USER_POSTS = 'PROFILE/SET_USER_POSTS';
export const SHOW_PROFILE_LOADING = 'PROFILE/SHOW_PROFILE_LOADING';
export const HIDE_PROFILE_LOADING = 'PROFILE/HIDE_PROFILE_LOADING';
export const REQUEST_FOLLOW = 'PROFILE/REQUEST_FOLLOW';
export const SET_FOLLOWERS = 'PROFILE/SET_FOLLOWERS';

export const UPDATE_PROFILE_POST = 'POST_CARD/UPDATE_PROFILE_POST';

export const REQUEST_ALL_POSTS = 'HOME/REQUEST_ALL_POSTS';
export const REQUEST_SUBSCRIBED_POSTS = 'HOME/REQUEST_SUBSCRIBED_POSTS';
export const SET_HOME_POSTS = 'HOME/SET_HOME_POSTS';

export const SHOW_POSTS_LOADING = 'POSTS/SHOW_POSTS_LOADING';
export const HIDE_POSTS_LOADING = 'POSTS/HIDE_POSTS_LOADING';

export const SET_USERS_LIST = 'USERS/SET_USERS_LIST';
export const REQUEST_GET_USERS_LIST = 'USERS/REQUEST_GET_USERS_LIST';
