export const REQUEST_LOGIN = 'AUTH/REQUEST_LOGIN';
export const REQUEST_REGISTER = 'AUTH/REQUEST_REGISTER';
export const SET_AUTH_USER = 'AUTH/SET_AUTH_USER';
export const SHOW_SESSION_LOADING = 'AUTH/SHOW_SESSION_LOADING';
export const HIDE_SESSION_LOADING = 'AUTH/HIDE_SESSION_LOADING';
